apiVersion: apps/v1
kind: Deployment
metadata:
  name: doyourchores-back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: doyourchores-back-label
  template:
    metadata:
      labels:
        app: doyourchores-back-label
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: doyourchores-back
          image: doyourchores.azurecr.io/doyourchores:backend
          env:
            - name: NODE_ENV
              value: "production"
            - name: DB_CONNECTION_STRING
              value: $(DB_CONNECTION_STRING)
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: doyourchores-back
spec:
  ports:
    - port: 5000
  selector:
    app: doyourchores-back
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doyourchores-front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: doyourchores-front-label
  template:
    metadata:
      labels:
        app: doyourchores-front-label
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: doyourchores-front
          image: doyourchores.azurecr.io/doyourchores:frontend
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: doyourchores-front
spec:
  type: LoadBalancer
  ports:
    - port: 3000
  selector:
    app: doyourchores-front
